// Sample property/room catalogue.
// Room markers use each room's lat/lng. In production this payload comes from a backend API.
// IMPORTANT: only room data uses coordinates — the user's Preferred Location is always geocoded dynamically.

export const roomsData = [
  {
    id: "wc-402",
    name: "Windsor Court",
    roomNumber: "Room 118-402",
    location: "Belgravia Square, London",
    city: "London",
    tier: "Single Room",
    price: 1850,
    availableFrom: "Aug 2026",
    status: "Available",
    lat: 51.4977,
    lng: -0.1544,
    desc: "Ground-floor access to private gardens with floor-to-ceiling windows and bespoke oak...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFyO66RgErN232FeilZH2elxl6dUKQzQCwz7kMPI25_B_zqHFPxheAh0NU2zRQgEl2agv64IuP7e9GFU7EbewFG0nviJ3nvhBS3cRTGChnfyts4qrq10rk-4YCLcWY1ZhG2Wxi4qMLov3ndhcbNDE0J2voRmmlNw44nP--b7ZQyPIobJZ6wjKWuIMepszpR3IESV4umSDhlJxKAvK1kdMfxiIJdp13gF-cRzpQb_TVAByVp7xbHqQ7XBKPY184WURbvHgIlM1FyCe3",
  },
  {
    id: "wc-110",
    name: "Windsor Court",
    roomNumber: "Room 110",
    location: "Belgravia Square, London",
    city: "London",
    tier: "Executive Suites",
    price: 2100,
    availableFrom: "Sep 2026",
    status: "Available",
    lat: 51.4993,
    lng: -0.1529,
    desc: "Ground-floor access to private gardens with floor-to-ceiling windows and bespoke oak...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCrHShwe7JVjLeFPePS011vva-4WwSUaYWV5ygzLfmFJ-1QIasieno8IAhojs7NeP_FhbFkKCLF5Qdih6wzSSKwIyHVP2vMQ92itA-HFrvHmFw48TbJnqv1QTlujyn3-c119QsHgqixYjks_nFLOOdQauE34fCTN_D_Sx_9xi-qiqEeguHCqByNmZmPTAbAoXRyd7t6tXXuDYMF6Fr2nWOK6xECzYjuYrRLlBzisOkT_H6uGxFiwK7nHXaKLMO0FGH1ngEScf6Ljj72",
  },
  {
    id: "ra-305",
    name: "Regent's Archive",
    roomNumber: "Room 305",
    location: "Marylebone Row, London",
    city: "London",
    tier: "Studio",
    price: 1975,
    availableFrom: "Aug 2026",
    status: "Available",
    lat: 51.5236,
    lng: -0.1518,
    desc: "Spacious studio with an integrated archive wall and museum-grade climate control for persona...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBZ6r6OMG9CmjAiC4QQPhrq5BXWuX2JGRfrVJ_-ixygu7jH4pFpbUVuDxnrKztf5cAibEJdDjiaXV1BjXt_tXkmXY6VqQySo8h6O6yiUOb6phnTr5eeVo-hhvt33-e-DxvB3DL4dFk2x93Gak6W1wwLJVjQMGIxEPgmK-yrSqJwSPB4OxDYyjgxm7AuJelwOaQHw9zyz4ib0ZiUyG_LhKJDmXjk70RwDKjfJ8-3tjPdo_bYsW1bj7PHVFnwqopCtHTz8Jt0DCqLtJS",
  },
  {
    id: "ra-306",
    name: "Regent's Archive",
    roomNumber: "Room 306",
    location: "Marylebone Row, London",
    city: "London",
    tier: "Single Room",
    price: 1975,
    availableFrom: "Oct 2026",
    status: "Available",
    lat: 51.5251,
    lng: -0.1503,
    desc: "Spacious studio with an integrated archive wall and museum-grade climate control for persona...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBZ6r6OMG9CmjAiC4QQPhrq5BXWuX2JGRfrVJ_-ixygu7jH4pFpbUVuDxnrKztf5cAibEJdDjiaXV1BjXt_tXkmXY6VqQySo8h6O6yiUOb6phnTr5eeVo-hhvt33-e-DxvB3DL4dFk2x93Gak6W1wwLJVjQMGIxEPgmK-yrSqJwSPB4OxDYyjgxm7AuJelwOaQHw9zyz4ib0ZiUyG_LhKJDmXjk70RwDKjfJ8-3tjPdo_bYsW1bj7PHVFnwqopCtHTz8Jt0DCqLtJS",
  },
  {
    id: "kk-208",
    name: "Kensington Keep",
    roomNumber: "Room 208",
    location: "Kensington High Street, London",
    city: "London",
    tier: "Executive Suites",
    price: 2400,
    availableFrom: "Sep 2026",
    status: "Available",
    lat: 51.5014,
    lng: -0.1908,
    desc: "Elegant suite overlooking private courtyard gardens with concierge service and quiet study spaces...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFyO66RgErN232FeilZH2elxl6dUKQzQCwz7kMPI25_B_zqHFPxheAh0NU2zRQgEl2agv64IuP7e9GFU7EbewFG0nviJ3nvhBS3cRTGChnfyts4qrq10rk-4YCLcWY1ZhG2Wxi4qMLov3ndhcbNDE0J2voRmmlNw44nP--b7ZQyPIobJZ6wjKWuIMepszpR3IESV4umSDhlJxKAvK1kdMfxiIJdp13gF-cRzpQb_TVAByVp7xbHqQ7XBKPY184WURbvHgIlM1FyCe3",
  },
  {
    id: "mc-vic",
    name: "Victoria Hall",
    roomNumber: "Room 514",
    location: "Deansgate, Manchester",
    city: "Manchester",
    tier: "Studio",
    price: 1450,
    availableFrom: "Aug 2026",
    status: "Available",
    lat: 53.4808,
    lng: -2.2446,
    desc: "Bright city-centre suite with skyline views and high-speed fibre, steps from Deansgate station...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCrHShwe7JVjLeFPePS011vva-4WwSUaYWV5ygzLfmFJ-1QIasieno8IAhojs7NeP_FhbFkKCLF5Qdih6wzSSKwIyHVP2vMQ92itA-HFrvHmFw48TbJnqv1QTlujyn3-c119QsHgqixYjks_nFLOOdQauE34fCTN_D_Sx_9xi-qiqEeguHCqByNmZmPTAbAoXRyd7t6tXXuDYMF6Fr2nWOK6xECzYjuYrRLlBzisOkT_H6uGxFiwK7nHXaKLMO0FGH1ngEScf6Ljj72",
  },
  {
    id: "bh-bull",
    name: "Bull Ring Residences",
    roomNumber: "Room 1204",
    location: "New Street, Birmingham",
    city: "Birmingham",
    tier: "Single Room",
    price: 1350,
    availableFrom: "Sep 2026",
    status: "Available",
    lat: 52.4778,
    lng: -1.8941,
    desc: "Modern studio in the heart of the city with panoramic views and 24/7 gym access...",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBZ6r6OMG9CmjAiC4QQPhrq5BXWuX2JGRfrVJ_-ixygu7jH4pFpbUVuDxnrKztf5cAibEJdDjiaXV1BjXt_tXkmXY6VqQySo8h6O6yiUOb6phnTr5eeVo-hhvt33-e-DxvB3DL4dFk2x93Gak6W1wwLJVjQMGIxEPgmK-yrSqJwSPB4OxDYyjgxm7AuJelwOaQHw9zyz4ib0ZiUyG_LhKJDmXjk70RwDKjfJ8-3tjPdo_bYsW1bj7PHVFnwqopCtHTz8Jt0DCqLtJS",
  },
];

export const DEFAULT_MAP_CENTER = { lat: 51.5074, lng: -0.1278 }; // London
export const DEFAULT_MAP_ZOOM = 5;

export const ROOM_MARKER_JITTER = 0.006;
